version: '3.8'

services:
  tts:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./outputs:/app/outputs
      - ./voices:/app/voices
      - ./text:/app/text
    environment:
      - FLASK_ENV=development
